BobinageArchive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bobinage.urls')),
    path('admin/', admin.site.urls),
]

bobinage/urls.py
# in urls.py of the application

from django.urls import path

from . import views

app_name = 'bobinage'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
]

bobinage/models.py
from django.db import models

# Create your models here.


class Archive(models.Model):
    marque = models.CharField(max_length=120, null=False, blank=False)
    CHEVEAUX_CHOICES = zip(range(1, 21), range(1, 21))
    Cheveaux = models.IntegerField(choices=CHEVEAUX_CHOICES, blank=False, null=False)
    TYPE_CHOICES = (
        ('Monophasé', 'Monophasé'),
        ('Triphasé', 'Triphasé')
    )
    type = models.CharField(max_length=120, choices=TYPE_CHOICES, blank=False, null=False)
    Amperage = models.PositiveIntegerField(blank=False, null=False)
    COUPLAGE_CHOICES = (
        ('Parallèle Etoile', 'Parallèle Etoile'),
        ('Parallèle Triangle', 'Parallèle Triangle'),
        ('Serie Etoile', 'Serie Etoile'),
        ('Serie Triangle', 'Serie Triangle')
    )
    couplage = models.CharField(max_length=120, choices=COUPLAGE_CHOICES, blank=False, null=False)
    nb_spire_principale =  models.PositiveIntegerField(blank=False, null=False)
    nb_spire_aux = models.PositiveIntegerField(blank=True, null=True)
    longeur_rotor_mm = models.PositiveIntegerField(blank=False, null=False)
    diametre_rotor_mm = models.PositiveIntegerField(blank=False, null=False)

bobinage/forms.py
from django import forms
from .models import Archive

class ArchiveCreateForm(forms.ModelForm):
    class Meta:
        model = Archive
        fields = '__all__'

bobinage/views.py
from django.shortcuts import render, redirect

# Create your views here.
from bobinage.forms import ArchiveCreateForm
from bobinage.models import Archive


def index(request):
    archives = Archive.objects.all()
    dictionary = {
        'archives': archives
    }
    return render(request, 'bobinage/index.html', dictionary)

def add(request):
    if request.method == "POST":
        form = ArchiveCreateForm(request.POST)
        if form.is_valid():
            archive = form.save(commit=False)
            archive.save()
            return redirect('bobinage:index')
    else:
        form = ArchiveCreateForm()
    return render(request, 'bobinage/add.html', {'form': form})

templates/bobinage/add.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <center><h1 class="mt-4">Ajouter un Archive</h1></center>
    <div class="row mb-5">
        <div class="col-8 offset-2">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Enregistrer</button>
                <button type="submit" class="btn btn-default">Annuler</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/bobinage/index.html
{% extends 'layout.html' %}

{% block stylesheets %}
{% endblock %}

{% block content %}
    <button id="btn-show-all-children" style="display:none" type="button">Expand All</button>
    <div class="container mt-3">
        <table id="example" class="display table table-hover table-sm" style="width:100%">
            <thead>
            <tr>
                <th>Marque</th>
                <th>Cheveaux</th>
                <th>Type</th>
                <th>Ampérage</th>
                <th>Couplage</th>
                <th>Spires</th>
                <th>Longeur Rotor</th>
                <th>Diamètre Rotor</th>
            </tr>
            </thead>
            <tbody>
            {% for archive in archives %}
                <tr>
                    <td>{{ archive.marque }}</td>
                    <td>{{ archive.Cheveaux }}</td>
                    <td>{{ archive.type }}</td>
                    <td>{{ archive.Amperage }}</td>
                    <td>{{ archive.couplage }}</td>
                    <td>{{ archive.nb_spire_principale }} {% if archive.nb_spire_aux %}| {{ archive.nb_spire_aux }}
                        (aux){% endif %}</td>
                    <td>{{ archive.longeur_rotor_mm }}</td>
                    <td>{{ archive.diametre_rotor_mm }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {

            var table = $('#example').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json"
                },
                searchHighlight: true,
                responsive: true,
                lengthMenu: [[-1, 10, 25, 50, 100, 200, 500], ["Tous", 10, 25, 50, 100, 200, 500]],
            });

            $('#btn-show-all-children').on('click', function () {
                // Expand row details
                table.rows(':not(.parent)').nodes().to$().find('td:first-child').trigger('click');
            });

            setTimeout(function(){ $("#btn-show-all-children").click() }, 500);

        });

    </script>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Bobinage</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/cosmo/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.20/datatables.min.css"/>
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/plug-ins/1.10.20/features/searchHighlight/dataTables.searchHighlight.css"/>
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css"/>

    {% block stylesheets %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'bobinage:index' %}">Bobinage Archive</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'bobinage:add' %}">Ajouter</a>
            </li>
        </ul>
    </div>
</nav>
{% block content %}{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/datatables.min.js"></script>
<script type="text/javascript" src="http://bartaz.github.io/sandbox.js/jquery.highlight.js"></script>
<script type="text/javascript"
        src="https://cdn.datatables.net/plug-ins/1.10.20/features/searchHighlight/dataTables.searchHighlight.min.js"></script>
<script type="text/javascript"
        src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script>
    var isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
    if (!isMobile) {
        widthRatio = 0.95;
        heightRatio = 0.65;
        var deg = 0;
        document.body.style.webkitTransform = 'rotate(' + deg + 'deg)';
        document.body.style.mozTransform = 'rotate(' + deg + 'deg)';
        document.body.style.msTransform = 'rotate(' + deg + 'deg)';
        document.body.style.oTransform = 'rotate(' + deg + 'deg)';
        document.body.style.transform = 'rotate(' + deg + 'deg)';
    }
</script>
{% block javascript %}{% endblock %}
</body>
</html>